### ISSUE TITLE
Error message during import of XML file

### ISSUE THREAD

**Issue by Liamhl** [linz/QGIS-LandXML-Plugin#4]
Hi there. 

I've got a problem importing XML date in QGIS. 
I've exported the XML data from an interactive PDF map view through Adobe Acrobat Pro DC. 
When I try to import the XML file into QGIS using the LandXML plugin I get the following error message:
"Problem importing xml 'name'" 
I've got no idea how to solve this. I've been reading up how to import XML data into QGIS but I haven't found another way. 

Thanks for any help you can provide.
Regards,

**Comment by ccrook** [comment]
Just now seen this :-(  Probably too late to comment, so closing.
