### ISSUE TITLE
crs unrecognized and line feature empty on import

### ISSUE THREAD

**Issue by okanisis** [linz/QGIS-LandXML-Plugin#5]
Hi, I've got a LandXML file and when I import it into QGIS 2.18.1 it imports an empty line feature and the CRS is also unrecognized.

I've attached the xml zipped for reference.

[Boundary.zip](https://github.com/linz/QGIS-LandXML-Plugin/files/619961/Boundary.zip)

Looks like it was generated from AutoCAD Civil 3D 2014.

**Comment by okanisis** [comment]
Just noticed that the plugin is for LINZ LandXML format and might not support other LandXML formats like this one, so just holding breath to see if other LandXML formats can be supported and this could be one of them!

**Comment by ccrook** [comment]
Hi Donovan

I'm going to be out of internet contact for next two weeks ... Will try and look at this over Xmas/ new year

Regards
Chris

________________________________
