### ISSUE TITLE
Mark id not populating

### ISSUE THREAD

**Issue by philwin1** [linz/QGIS-LandXML-Plugin#7]
When reading LandOnLine XML the mrk_id is not populated when point name is for example, [26838069]

**Comment by ccrook** [comment]
@philwin1 Thanks for reporting.  Are you able to supply an example XML file please?

**Comment by philwin1** [comment]
The XML format is not accepted as an attachment type so I have renamed the extension to txt. I've also attached a screen shot of the data set. I've only just started taking notice of this parameter but the problem exists on all examples I've tried to date. Many thanks - no rush.
[Extract_2939890.txt](https://github.com/linz/QGIS-LandXML-Plugin/files/2536058/Extract_2939890.txt)
 and screen shot
![mark id](https://user-images.githubusercontent.com/44630432/47813498-2801f680-ddb0-11e8-8373-3a662777e829.jpg)

**Comment by ccrook** [comment]
@philwin1 This should be fixed now - please let me know if you still have issues.  Thanks for reporting this

**Comment by philwin1** [comment]
Thanks Chris,
The new version works great reading a LINZ XML extract file however it no longer works with an XML file exported from 12d. The attached XML file works with QGIS 2.18 LandXML v1.5 but not with QGIS 3.4.1 and LandXML v2.1. A while ago you modified LandXML to populate the 12d id attribute.  Thanks for your work.
[TSS Final 20181026.txt](https://github.com/linz/QGIS-LandXML-Plugin/files/2564225/TSS.Final.20181026.txt)


![landxml12derror](https://user-images.githubusercontent.com/44630432/48236742-7fdfd380-e428-11e8-8a6a-c14dd91953d3.JPG)

**Comment by ccrook** [comment]
Thanks ... very careless.  Fixed in 2.2/1.7

**Comment by philwin1** [comment]
Great, it works on both sources of data. Thanks a lot.
