### ISSUE TITLE
Problem importing xml 'name'

### ISSUE THREAD

**Issue by bipo76** [linz/QGIS-LandXML-Plugin#8]

**Comment by bipo76** [comment]
Dear plugin developer!

I tried to import a LandXml file - from AutoCAD Civil 3D and get this error:
Problem importing xml 'name' 
-> is there a workaround to fix this issue?
Attached is the zipped xml-file.
[dgm_dorfbach.zip](https://github.com/linz/QGIS-LandXML-Plugin/files/2579415/dgm_dorfbach.zip)

Thanks - Kind regards !

**Comment by ccrook** [comment]
@bipo76 Hi, Thanks for raising issue and for supplying test data.  
Unfortunately the Xml file you have supplied is not compatible with this plugin.  Not that there is anything wrong with it - just that the plugin only supports a limited subset of the LandXml schema.   It is written for New Zealand specific application and unfortunately I don't have the time to generalize it.
I'm sorry I can't help with this.
